language: php
php:
  - '7.1'

services:
  - mysql

install:
  - composer install
  - cat test_config.php > config.php
  - mysql < sql.sql

script:
  - vendor/bin/phpunit tests/phpunit
  - vendor/bin/codecept run acceptance
